# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: dm_web_seg.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'dm_web_seg.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x64m_web_seg.proto\x12\x10\x62ilibili.danmaku\"\xdf\x02\n\x0b\x44\x61nmakuElem\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x10\n\x08progress\x18\x02 \x01(\x05\x12\x0c\n\x04mode\x18\x03 \x01(\x05\x12\x10\n\x08\x66ontsize\x18\x04 \x01(\x05\x12\r\n\x05\x63olor\x18\x05 \x01(\r\x12\x0f\n\x07midHash\x18\x06 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x07 \x01(\t\x12\r\n\x05\x63time\x18\x08 \x01(\x03\x12\x0e\n\x06weight\x18\t \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\n \x01(\t\x12\x0c\n\x04pool\x18\x0b \x01(\x05\x12\r\n\x05idStr\x18\x0c \x01(\t\x12\x0c\n\x04\x61ttr\x18\r \x01(\x05\x12\x11\n\tanimation\x18\x16 \x01(\t\x12\x0b\n\x03mid\x18\x19 \x01(\x03\x12\x0f\n\x07\x64m_type\x18\x1a \x01(\x05\x12\r\n\x05\x64m_id\x18\x1b \x01(\x03\x12\x0b\n\x03uid\x18\x1e \x01(\x03\x12\x18\n\x10show_flow_weight\x18\x1f \x01(\x03\x12\x12\n\nshow_count\x18  \x01(\x03\x12\x0c\n\x04\x64mid\x18$ \x01(\x03\"\x8f\x01\n\x10\x44mSegMobileReply\x12,\n\x05\x65lems\x18\x01 \x03(\x0b\x32\x1d.bilibili.danmaku.DanmakuElem\x12\x30\n\x08web_info\x18\x02 \x01(\x0b\x32\x1e.bilibili.danmaku.DmSegWebInfo\x12\x1b\n\x13visible_danmaku_num\x18\x03 \x01(\x05\"I\n\x0c\x44mSegWebInfo\x12\x14\n\x0c\x64m_need_scan\x18\x01 \x01(\x05\x12\x11\n\tscan_type\x18\x02 \x01(\t\x12\x10\n\x08scan_end\x18\x03 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'dm_web_seg_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DANMAKUELEM']._serialized_start=39
  _globals['_DANMAKUELEM']._serialized_end=390
  _globals['_DMSEGMOBILEREPLY']._serialized_start=393
  _globals['_DMSEGMOBILEREPLY']._serialized_end=536
  _globals['_DMSEGWEBINFO']._serialized_start=538
  _globals['_DMSEGWEBINFO']._serialized_end=611
# @@protoc_insertion_point(module_scope)
